### PR TITLE
Add ability to send emails on exceptions (fix #207)

### LINKED ISSUE #207: Re-enable Exception Emails
See https://github.com/arborrow/montserrat/blob/master/app/Exceptions/Handler.php which someone (@Djaw ) removed.

### PR DESCRIPTION
**Pull request by AtaGowani**
Fixes #207

### CODE REVIEW

**Comment by arborrow** [comment]
By checking if the method exists we can then avoid using the getStatusCode in the emails error blade file which may have been hanging things up. When there are no errors displayed on the screen, it can be helpful to check the laravel log. Peace - Anthony

**Comment by AtaGowani** [comment]
So the reason why localhost was showing 500 error is because the render function was not returning properly for it to display the exception. The Mailer was going into a callback which disregarded the return at the very end. I added a return at the end of the callback function so that once the email is sent it can render the page.

**Comment by arborrow** [comment]
So on my non-vagrant/homestead install where it is not root here is some behavior that i am seeing. First, when I am not logged in and go to the root path https://localhost/polanco I simply get a blank screen. In the laravel.log file it has an error:

production.ERROR: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method ErrorException::getStatusCode() in /var/www/p54/storage/framework/views/40e535293ebe6493a332b18e986af39ad33e2361.php:1

Similarly, when I try to test the 403 by logging in as MManager (which cannot create a person) i get a blank screen and a similar error message. 

The email notification does work for a 404. Have you been able to test the various errors (403. 404, 500) and get them to work?

**Comment by arborrow** [comment]
Here was an unexpected additional email I received:

 Polanco 404 Error Detected
User Details
Username: Unknown user

URL: http://localhost/polanco/dist/popper.js.map

**Comment by arborrow** [comment]
The more I look at this code and work on it the more I see the necessity for checking the type of exception and just catching the ones that we want. Otherwise I am afraid we leave ourselves vulnerable to some rather buggy behavior. 

For the home page, there was an exception thrown before logging in and it returns an Unauthenticated message. We could test if when it is not Unauthenticated and then go through the various steps to build the email; however, I noticed that when a 403 issue is thrown it does not have a getStatusCode. We could simply ignore the fact that a 403 does not have a status code and simple use the message - it provides me the same information although I sort of liked how the code worked before. In any case, here is something that may work: 
```php
public function render($request, Exception $exception)
    {
		$fullurl = $request->fullUrl();
		$ip_address = 'Unspecified IP Address';
		$username = 'Unknown user';
		$subject =  'Error Detected on ' . config('polanco.site_name');
        // dd($exception->getMessage()!=="Unauthenticated");
        if ($exception->getMessage()!=="Unauthenticated") {

    		if (isset(Auth::User()->name)) {
    			$username = Auth::User()->name;
    		}

    		if (!empty($request->ip())) {
    			$ip_address = $request->ip();
    		}

    		if (method_exists($exception, 'getStatusCode')) {
    			$subject .= ': ' . $exception->getStatusCode();
    		} else if (method_exists($exception,'getMessage')) {
                $subject .= ': ' . $exception->getMessage();
            }
            dd($subject,$exception);
    		Mail::send('emails.error', ['error' => $exception, 'url' => $fullurl, 'user' => $username, 'ip' => $ip_address, 'subject' => $subject], function ($m) use ($subject, $exception, $request) {
    			$m->to(config('polanco.admin_email'))->subject($subject);
    			return parent::render($request, $exception);
    		});
        }
		return parent::render($request, $exception);
```
Let me know what you think.

**Comment by arborrow** [comment]
I was looking at the various types of exceptions we are using here in this file. All of those will produce an email which is not necessarily a bad thing but the original intention was to notify on 403, 404 and 500. Other errors, such as validation errors on a form would be sent with this code. We really need to consider how each of those exceptions are constructed (with or without a status code, etc.) and which ones we don't want to have an email sent on.

**Pull request merged**
