### PR TITLE
Clean up and re-organize frontend (fix #227)

### LINKED ISSUE #194: Evaluate creation of a menu system

### LINKED ISSUE #227: Clean up public assets
## Description
Clean up the css/js frontend assets to make frontend development less confusing.

### LINKED ISSUE #261: Gate UI
I find the current Gate UI feels like it is invading Polanco. Let's move it up as a drop down menu once you get the UI changes done.

### PR DESCRIPTION
**Pull request by AtaGowani**
Fixes #227, Fixes #194, Fixes #261 
### Changes Made
* Re-organized CSS/JS files
* Updated UI 
* Switched over to Bootstrap 4
#### Person
- [x] Edit Person
- [x] Add touchpoint
#### Parish
- [x] Index
- [x] Show Parish
- [x] Edit Parish
#### Diocese
- [x] Index
- [x] Show Diocese
- [x] Edit Diocese
- [x]  Create Diocese
#### Organization
- [x] Index
- [x] Show Org
- [x] Edit Org
- [x] Create Org
#### Vendors
- [x] Show Vendors
- [x] Edit Vendors
- [x] Index
- [x] Create
### Event
- [x] Show Event
- [x] Edit Event
### Room
Looks good
### Donation
- [x] Index
- [x] Create Donation
- [x] View donations
- [x] Edit
### Payment
- [x] Create
- [x] Show
- [x] Edit
#### Role
- [x] Create role
- [x] Index
- [x] Edit
- [x] Show
#### Permission
- [x] Edit Permission
- [x] Show Permission
- [x] Index
- [x] Create
## Finance
- [x] agc/2019

#### Person
- [x] Index
- [x] Show person
- [x] Add person
- [x] Remove person
- [ ] Edit person
- [ ] Add touchpoint
#### Parish
- [ ] Index
- [ ] Show Parish
- [ ] Edit Parish
- [ ] Add Parish
- [ ] Remove Parish
#### Diocese
- [ ] Index
- [ ] Show Diocese
- [ ] Edit Diocese
- [ ] Create Diocese
- [ ] Delete Diocese
#### Organization
- [ ] Index
- [ ] Show Org
- [ ] Edit Org
- [ ] Create Org
- [ ] Delete Org
#### Vendors
- [ ] Index
- [ ] Show Vendor
- [ ] Edit Vendor
- [ ] Create Vendor
### Event
- [ ] Index
- [ ] Show Event
- [ ] Edit Event
- [ ] Create Event
- [ ] Delete Event (?)
### Room
- [ ] Index
### Donation
- [ ] Index
- [ ] Create Donation
- [ ] View Donation
- [ ] Delete Donation (?)
- [ ] Edit Donation
### Payment
- [ ] Create Payment
- [ ] Show Payment
- [ ] Edit Payment
- [ ] Delete Payment (?)
#### Role
- [ ] Index
- [ ] Create Role
- [ ] Edit Role
- [ ] Show Role
- [ ] Delete Role
#### Permission
- [ ] Index
- [ ] Edit Permission
- [ ] Show Permission
- [ ] Create Permission
- [ ] Delete Permission
## Finance
- [ ] agc/2019 index

#### Person
- [x] Index
- [x] Show person
- [ ] Add person
- [x] Remove person
- [ ] Edit person
- [x] Add touchpoint
#### Parish
- [x] Index
- [x] Show Parish
- [x] Edit Parish
- [x] Add Parish
- [x] Remove Parish
#### Diocese
- [ ] Index
- [ ] Show Diocese
- [ ] Edit Diocese
- [ ] Create Diocese
- [ ] Delete Diocese
#### Organization
- [ ] Index
- [ ] Show Org
- [ ] Edit Org
- [ ] Create Org
- [ ] Delete Org
#### Vendors
- [ ] Index
- [ ] Show Vendor
- [ ] Edit Vendor
- [ ] Create Vendor
### Event
- [ ] Index
- [ ] Show Event
- [ ] Edit Event
- [ ] Create Event
- [ ] Delete Event (?)
### Room
- [ ] Index
### Donation
- [ ] Index
- [ ] Create Donation
- [ ] View Donation
- [ ] Delete Donation (?)
- [ ] Edit Donation
### Payment
- [ ] Create Payment
- [ ] Show Payment
- [ ] Edit Payment
- [ ] Delete Payment (?)
#### Role
- [ ] Index
- [ ] Create Role
- [ ] Edit Role
- [ ] Show Role
- [ ] Delete Role
#### Permission
- [ ] Index
- [ ] Edit Permission
- [ ] Show Permission
- [ ] Create Permission
- [ ] Delete Permission
## Finance
- [x] agc/2019 index

### CODE REVIEW

**Comment by arborrow** [comment]
Just to let you know that I am not necessarily committed to any of the current UI, styling, etc. If you have ideas for improvements this is an area that I'm very open to improvements. I don't want you to feel constrained by the current implementation.

**Comment by AtaGowani** [comment]
This also fixes #194 in this

**Comment by AtaGowani** [comment]
@arborrow 
Running into a bug locally when creating an organization. While debugguging found this query to pull up all the organizations. Why is it that it's checking not only the contact_type but also the subcontact_type of a contact to determine whether it is an organization or not?
```
['contact_type','>=',config('polanco.contact_type.organization')],
['subcontact_type','>=',config('polanco.contact_type.province')]
```

**Comment by AtaGowani** [comment]
> @arborrow
> Running into a bug locally when creating an organization. While debugguging found this query to pull up all the organizations. Why is it that it's checking not only the contact_type but also the subcontact_type of a contact to determine whether it is an organization or not?
> 
> ```
> ['contact_type','>=',config('polanco.contact_type.organization')],
> ['subcontact_type','>=',config('polanco.contact_type.province')]
> ```

Nevermind I figured it out. Organization does not encompass `vendor, retreat_house, etc.`

**Comment by AtaGowani** [comment]
The error was caused because under the dropdown when creating an organization I have it a type `diocese`. Which according to our query is not an organization. Both `parish` and `diocese` are options in the dropdown but should not be since if created using those option they will never be shown on the user end. I'm going to remove those two options let me know if you think we need them.
screen shot 2018-11-18 at 1 07 23 pm

**Comment by arborrow** [comment]
So I noticed that the persons.show blade images (like the groups - board, staff, etc.) are not showing. I also noticed that the new envelope and letter images are still in an img folder rather than images. What is your recommendation about the best way of creating those image links (url vs asset)? The easiest thing would be to simply search and replace img and replace it with images. In general the formatting at the top of the page leads a little tweaking. Try adding the user to some of the various groups and see what it looks like.

**Comment by arborrow** [comment]
In the person update address, email, etc. it looks like I was using things like fa-archive. I'm not sure what version of font-awesome I was intending to use or where the best place to add it is but it would be nice if they worked.

**Comment by arborrow** [comment]
Here is a grep of img/ from the resource views which will give you a checklist of all the places where the image source needs to be converted to get the image from the compiled assets (public/images). 
[polanco-img.txt](https://github.com/arborrow/montserrat/files/2755364/polanco-img.txt)

**Comment by arborrow** [comment]
As best I can tell, the event start and end dates are not working - we want those to be date/time entries. We should probably go through each of the forms looking for dates and datetimes and make sure that they are being handled properly. I really want to to be able to move on past this issue. Do you think that we might be able to pick up the pace a little?

**Comment by arborrow** [comment]
How much of this documentation should we have in the README? Is there a way of checking that the correct versions are installed - should we have a recommended version of composer, nodejs, npm, and yarn?

#install nodejs 10 with npm 6.4.1
curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install -y nodejs
#install yarn version 1.13.0
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install yarn

# remove vendor files
# remove node_modules
composer install
yarn install
npm run dev

**Comment by AtaGowani** [comment]
## Stuff that needs to be fixed
### Contact
#### Person
- [ ] Edit Person
#### Parish
- [ ] Show Parish
- [ ] Edit Parish
#### Diocese
- [ ] Show Diocese
- [ ] Edit Diocese
- [ ]  Create Diocese
#### Organization
- [ ] Show Org
- [ ] Edit Org
- [ ] Create Org
#### Vendors
- [ ] Show Vendors
- [ ] Edit Vendors
### Event
- [ ] Show Event
- [ ] Edit Event
### Room
*has not been checked properly due to not having development data*
### Donation
- [ ] Create Donation
### Admin
#### Role
- [ ] Create role
#### Permission
- [ ] Edit Permission
- [ ] Show Permission

**Comment by AtaGowani** [comment]
When testing, we'll need to make sure we are testing with different permissions level to make sure the security has not been compromised due to any typos.

**Comment by arborrow** [comment]
I noticed that when viewing a contact that the anchor links to Registration, Touchpoint, Donation and the various subsections was not working. We should probably have anchor ids working so as to help avoid scroll of death. Additionally, we should probably work toward having a limited number of items displayed by default and then expanding the sections when more is needed (in particular, registration sections for a contract group can get quite long) and folks that we have a lot of interaction with can have long touchpoint sections.

**Comment by arborrow** [comment]
On persons show blade, I believe that we still need the id=donations attribute added so that the link to the donations anchor will work properly. The others are working nicely but I know that the finance office makes use of the donations one regularly. Peace - Anthony

**Comment by AtaGowani** [comment]
> On persons show blade, I believe that we still need the id=donations attribute added so that the link to the donations anchor will work properly. The others are working nicely but I know that the finance office makes use of the donations one regularly. Peace - Anthony

Fixed!

**Comment by arborrow** [comment]
Looking at the Address section on person show blade it no longer seems to give a good Address header to the section (I think visually it might be helpful to have Address(es) , Phone number(s), and E-Communication(s), etc.) Also, I noticed that when there is more than one address they can get displayed on the same line (Home and Other). It may be good to have a line break after each address so that visually they are easier to distinguish.

**Comment by AtaGowani** [comment]
> @AtaGowani - I am not sure why Atom had these changes to be pushed - I was actually trying to do a pull on the wip-227 branch. I thought I had everything pulled in properly, could you please check this commit as it looks related to stuff that you were doing today and make sure they are desired changes or feel free to simply undo any or all of it. Peace - Anthony

All looks good!

**Comment by arborrow** [comment]
Fontawesome seems to assume that the fonts are in the root - on my one installation where I am using http://localhost/polanco it fails to find the fonts because it looks in http://localhost/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff2?59ea9019c9b9bc4d83ab9783e830735c rather that localhost/polanco/fonts ... - I am not sure where best to specify the path to the fonts so that it includes the app root rather than server root.

**Comment by AtaGowani** [comment]
> Fontawesome seems to assume that the fonts are in the root - on my one installation where I am using http://localhost/polanco it fails to find the fonts because it looks in http://localhost/fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff2?59ea9019c9b9bc4d83ab9783e830735c rather that localhost/polanco/fonts ... - I am not sure where best to specify the path to the fonts so that it includes the app root rather than server root.

Hmmm will look into this

**Comment by AtaGowani** [comment]
We are ready for testing!!

**Comment by arborrow** [comment]
I'd like to start making use of a CHANGELOG.md and perhaps documenting in there when we have made fixes to security issues with references to CVE of the issue. Perhaps you can review https://keepachangelog.com/en/1.0.0/ and we can start doing this as we move forward.

**Pull request merged**
