### PR TITLE
Laravel 5.3 Shift

### PR DESCRIPTION
**Pull request by arborrow**
This pull request includes the changes for upgrading to Laravel 5.3. Feel free to commit any additional changes to the `shift-3173` branch.

**Before merging**, you should:

- Checkout the `shift-3173` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the pre-commands fail, add `--no-scripts`)
- Thoroughly test your application

If you would like more help with your upgrade, check out the [human services from Laravel Shift](https://laravelshift.com/human-services). And if you want to level-up your Git skills, check out [Getting Git](https://gettinggit.com).

### CODE REVIEW

**Comment by arborrow** [comment]
ℹ Laravel 5.3 updated the  `app/Jobs` folder by default. It is created for you when you make your first *Job* using `artisan`. Shift did not remove yours as it appears to differ from the default. However, if your app does not use *Jobs*, you can remove this folder manually to keep your app streamlined.

**Comment by arborrow** [comment]
ℹ Laravel 5.3 no longer includes the `app/Events` folder by default. It is created for you when you make your first *Event* using `artisan`. Shift did not remove yours as it appears to differ from the default. However, if your app does not use *Events*, you can remove this folder manually to keep your app streamlined.

**Comment by arborrow** [comment]
❌ Laravel 5.3 split the `Auth/AuthController.php` into the `Auth/LoginController.php` and the `Auth/RegisterController.php`. Since yours appears to be customized, Shift did not remove it. You should compare your `Auth/AuthController.php` with the newly added controllers and merge your changes accordingly.

**Comment by arborrow** [comment]
❌ Laravel 5.3 renamed the `Auth/PasswordController.php` to `Auth/ResetPasswordController.php`. Since yours appears to be customized, Shift did not remove it. You should compare your `Auth/PasswordController.php` against the added `Auth/ResetPasswordController.php` and merge your changes accordingly.

**Comment by arborrow** [comment]
⚠ If you are using *Authentication*, you should upgrade any routes using `AuthController` and `PasswordController` to use the new authentication controllers. Laravel recommends using the `Auth::routes()` which registers the proper routes for the new authentication controllers. This method also registers a `POST` route for `/logout` instead of a `GET` route.

**Comment by arborrow** [comment]
❌ Shift could not upgrade `app/Providers/AuthServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/AuthServiceProvider.php) and merge the new changes.

**Comment by arborrow** [comment]
❌ Shift could not upgrade `app/Providers/EventServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/EventServiceProvider.php) and merge the new changes.

**Comment by arborrow** [comment]
❌ Shift could not upgrade `app/Providers/RouteServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/RouteServiceProvider.php) and merge the new changes.

**Comment by arborrow** [comment]
❌ Laravel 5.2 introduced *Middleware Groups*, which are now used in Laravel 5.3. It appears you have not upgraded to *Middleware Groups*. You should review [Middleware Groups](http://laravel.com/docs/5.3/middleware#middleware-groups) in more detail. Then compare your `app/Http/Kernel.php` with the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Http/Kernel.php) and update manually.

**Comment by arborrow** [comment]
⚠ Laravel 5.3 now includes a top-level `routes` folder. In addition, it separates routes into *API*, *console*, and *web* files.Shift included a default `routes/api.php` and `routes/console.php` as well as migrated your `app/Http/routes.php` to `routes/web.php`. You should review your routes to see if they should be separated into one of the new route files.

**Comment by arborrow** [comment]
⚠ The default behavior of `Route::resource()` changed in Laravel 5.3. All resource route parameters are now singularized by default and URL prefixes no longer affect the route names.You should review your resource routes and verify this singularized naming will not affect your parameters (or if you were doing this manually, you can remove the `parameter`). In addition, verify you are no longer appending the URI prefix to the route name.

Found `Route::resource()` in:

- [ ] routes/web.php

**Comment by arborrow** [comment]
❌ In Laravel 5.3, the `first`, `last`, and `contains` methods now pass the *value* as the first parameter to the given callback instead of the *key*. You should verify these callbacks are still working properly.

Shift found potential uses of these methods in:

- [ ] app/HasRoles.php

**Comment by arborrow** [comment]
❌ In Laravel 5.3, the outer-most parenthesis are not included in the *expression* passed to your `Blade::directive()` callback. You should verify your custom Blade directives are still working properly.

Shift found `Blade::directive()` in:

- [ ] app/Providers/EntrustCustomServiceProvider.php

**Comment by arborrow** [comment]
❌ Shift could not upgrade the following configuration files since they differed from the default Laravel version. You will need to compare these configuration files against the [Laravel 5.3 configuration files](https://github.com/laravel-shift/laravel-5.3/blob/master/config) and merge any changes:

- [ ] config/auth.php
- [ ] config/mail.php
- [ ] config/services.php

**Comment by arborrow** [comment]
❌ Shift could not upgrade the following project files since they differed from the default Laravel version. You will need to compare these project files against the [default Laravel 5.3 versions](https://github.com/laravel-shift/laravel-5.3/) and merge any changes:

- [ ] gulpfile.js

**Comment by arborrow** [comment]
❌ Laravel 5.3 `where` performs a "loose" comparison. In addition, the *strict* parameter was removed. If you need to perform a "strict" comparison, you can use `whereStrict` instead.

You should review the following usages of `where` to ensure you do not require "strict" compaison:

- [ ] app/Contact.php
- [ ] app/UserRepository.php
- [ ] app/Http/Controllers/RelationshipTypesController.php
- [ ] app/Http/Controllers/PagesController.php
- [ ] app/Http/Controllers/RegistrationsController.php
- [ ] app/Http/Controllers/PermissionsController.php
- [ ] app/Http/Controllers/RetreatsController.php
- [ ] app/Http/Controllers/ParishesController.php
- [ ] app/Http/Controllers/PersonsController.php
- [ ] app/Http/Controllers/SearchController.php
- [ ] app/Http/Controllers/MailgunController.php
- [ ] app/Http/Controllers/DiocesesController.php
- [ ] app/Http/Controllers/TouchpointsController.php
- [ ] app/Http/Controllers/RoomsController.php
- [ ] app/Retreat.php
- [ ] app/ContactType.php
- [ ] routes/web.php

**Comment by arborrow** [comment]
❌ In Laravel 5.3, Eloquent scopes now respect the leading boolean of scope constraints. If you are starting your scope with an `orWhere` constraint it will no longer be converted to a normal `where`.

You should review the following usages of `orWhere` to ensure you're not starting your constraints with it:

- [ ] app/Contact.php

**Comment by arborrow** [comment]
❌ In Laravel 5.3, the `JoinClause` class has been rewritten to unify its syntax with the query builder. The optional `$where` parameter of the `on` clause and the `bindings` property have been removed.

You should review the following usages of `join` to ensure you're not using these features:

- [ ] app/Http/Controllers/PagesController.php

**Comment by arborrow** [comment]
❌ The Query Builder returns collections, instead of plain arrays, in Laravel 5.3. You will need to upgrade your code to use collections or chain the `all()` method onto your query to return a plain array.

You should review the following usages of Query Builder:

- [ ] app/Http/Controllers/PagesController.php
- [ ] app/Http/Controllers/RegistrationsController.php
- [ ] app/Http/Controllers/TouchpointsController.php
- [ ] database/migrations/2016_08_29_100000_create_attachments.php

**Comment by arborrow** [comment]
ℹ If you are using *Queues*, you no longer need to specify the `--daemon` option when calling the `queue:work`. This is assumed in Laravel 5.3. Use the `--once` option to process a single job.

**Comment by arborrow** [comment]
ℹ If you are using the `database` driver for your *Queue*, you will need to update your `jobs` and `failed_jobs` table. Review the *Queue* section of the [Laravel 5.3 Upgrade Guide](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0) for more details and feel free to use the [migrations from Laravel Shift](https://github.com/laravel-shift/laravel-5.3/tree/master/database/migrations).

**Comment by arborrow** [comment]
ℹ Laravel 5.3 updated several of the default assets as well as adding support for [Vue.js](https://vuejs.org). If you are using Laravel to [compile assets](https://laravel.com/docs/5.3/elixir) you may want to review the latest versions of [`resources/assets/js/app.js`](https://github.com/laravel-shift/laravel-5.3/blob/master/resources/assets/js/app.js) and [`resources/assets/sass/app.scss`](https://github.com/laravel-shift/laravel-5.3/blob/master/resources/assets/sass/app.scss) and update your project accordingly.

**Comment by arborrow** [comment]
⚠ Laravel 5.3 added configuration for your application name in `config/app.php`. Be sure to set this value as it is used in notifications, like the password reset email.

**Comment by arborrow** [comment]
❌ PHP syntax errors were detected after running your Shift. Often these are misplaced lines due to an unexpected code format.

I found PHP syntax errors in:

- [ ] app/Exceptions/Handler.php

**Comment by Djaw** [comment]
Project is now at Laravel 5.6 on branch polanco_56. This pull request is no longer needed.

**Pull request closed without merging**
