### PR TITLE
Add documentation for Twilio setup (fix #239)

### LINKED ISSUE #239: Update documentation to include Twillio configurations
## Description
Currently, when updating contact/person information (phone number) an error is thrown because `TWILIO_SID` and `TWILIO_TOKEN` are not set locally. We need to update the documentation so that the developer can set up a Twilio and set those env variables in `.env`

### PR DESCRIPTION
**Pull request by AtaGowani**
## Description
Added instructions to update `.env` to include Twilio variables.
## Issue
See #239

### CODE REVIEW

**Comment by AtaGowani** [comment]
@arborrow I am not sure about what the `TWILIO_NUMBER` env variable is for and where to access the value corresponding to it. Is this a number that you have already added to your Twilio account?

**Comment by arborrow** [comment]
Yes, it is the twilio assigned number, similar to a Google Voice number. Does that make sense?

**Comment by arborrow** [comment]
Yes, it is the twilio assigned number, similar to a Google Voice number. Does that make sense?

**Comment by AtaGowani** [comment]
Change this up to doing a check in the code base. If the env variable does not exist then it should go ahead and not do the Twilio verification.

**Comment by arborrow** [comment]
You may wish to set up a separate issue for ensuring that the validation requests are conditional upon twillio being set up but doing so would avoid the 'breakage' effect of not being able to add users. Similarly, as we chatted about, checking for the Google calendar integration before saving an event (retreat) would be helpful as well. Just let me know when you want me to review this pull request.

**Comment by arborrow** [comment]
This has been sitting around for a while. I went ahead and manually merged into README file and will close this issue and mark #239 as fixed.

**Pull request closed without merging**
